!!python/object:argparse.Namespace
augment: !!python/object:argparse.Namespace
  n_samples: 20
  models:
  - gt_graph
  - AdaSyn
  model_params: !!python/object:argparse.Namespace
    tabDiffusion: !!python/object:argparse.Namespace
      batch_size: 4096
      dropout: 0.0
      hidden_dim_layer:
      - 512
      - 256
      dim_t: 128
      num_timesteps: 1000
      gaussian_loss_type: kl
      lr: 0.001
      fold: 5
      is_y_cond: false
      epochs: 60000
      eval_freq: 10000
      print_freq: 5000
    gt_graph: !!python/object:argparse.Namespace
      kwarg: None
    SMOTE: !!python/object:argparse.Namespace
      k_neighbors: 5
    AdaSyn: !!python/object:argparse.Namespace
      n_neighbors: 5
ori: !!python/object:argparse.Namespace
  n_samples:
  - 200
  n_points:
  - 10
  exp_degree:
  - 3
  causal_mechanism:
  - polynomial
  - nn
  noise_coeff: 1.0
  noise_type:
  - Cauchy
  - GaussianMixture5
  root:
  - Gaussian
  replicates: 4
  graph_num: 1
  designate: true
  dag_type: erdos
  weight_distribution_function: normal
  weight_kwargs: !!python/object:argparse.Namespace
    mu: 0
    sigma: 1
    clip: 0.1
  mechanism_kwargs: !!python/object:argparse.Namespace
    rescale: false
    hidden_layer_num: 5
    activation_function: Tanh
    nh: 20
    d: 3
  copula_trans: false
  copula_trans_kwargs: !!python/object:argparse.Namespace
    dfn: 3
    dfd: 3
weight_kwargs:
  mu: 0
  sigma: 1
  clip: 0.1
seed: 8888
